language: node_js;
node_js: "node"
services: "postgresql"



# install additional dependencies required by the project
before_install:


install:
 -"yarn"
 -"npm install"

before_script:
  # Create a database for your application
  - psql -c 'create database travis_ci_test;' -U postgres
  # Activate PostGIS extension
  - psql -U postgres -c "create extension postgis"


script:
  - "start"
  - "test"


# optional before_deploy
# optional deploy:
  # skip_cleanup: true
# optional after_deploy
# after_script: 